In [1]:
file="F:\Equity Research project\Wallmart_Financial_Report.xlsx"

In [2]:
import logging
logging.disable(logging.CRITICAL)

In [3]:
from config import api_key, endpoint

In [4]:
import pandas as pd
import numpy as np
import re
import spacy

from sentence_transformers import SentenceTransformer, util
from financial_parsing_horizontal import extract_financial_data

============================================================
            FINANCIAL DATA PARSER CONFIGURATION
============================================================

Are you experienced in financial domain analysis? (yes/no):  no

HITL REVIEW MODE: DISABLED
System will operate in fully automatic mode
============================================================

In [5]:
#### import pandas as pd

import pandas as pd
import numpy as np
def select_sheets(file_path):
    xls = pd.ExcelFile(file_path)
    
    print("📄 Available Sheets in File:")
    sheet_names = xls.sheet_names
    for i, name in enumerate(sheet_names):
        print(f"{i}: {name}")
    
    print("\nEnter the sheet number for the financial statements you have:")
    print("If you don't have one, just press Enter.\n")

    income_idx = input("📊 Income Statement: ")
    balance_idx = input("📘 Balance Sheet: ")
    cashflow_idx = input("💸 Cash Flow Statement: ")

    income_statement = None
    balance_sheet = None
    cash_flow = None

    if income_idx.strip() != "":
        income_statement = pd.read_excel(xls, sheet_name=sheet_names[int(income_idx)])
    if balance_idx.strip() != "":
        balance_sheet = pd.read_excel(xls, sheet_name=sheet_names[int(balance_idx)])
    if cashflow_idx.strip() != "":
        cash_flow = pd.read_excel(xls, sheet_name=sheet_names[int(cashflow_idx)])

    print("\n✅ Selected sheets loaded successfully.")
    return income_statement, balance_sheet, cash_flow

# Preview
file_path = file  # replace `file` with your actual path or file upload logic
income_df, balance_df, cashflow_df = select_sheets(file_path)

if income_df is not None:
    print("\n📊 Income Statement Preview:")
    display(income_df.head())
   # income_df,layout_income=smart_layout_parser(income_df)
   # print(f"\n📊 Income Statement Preview (Layout: {layout_income}):")
   # display(income_df.head())
    #income_map = parse_statement(income_df, 'income')
    #print("Mapped keys:", list(income_map.keys()))

if balance_df is not None:
    print("\n📘 Balance Sheet Preview:")
    display(balance_df.head())
    #balance_df, layout_balance = smart_layout_parser(balance_df)
    #print(f"\n📘 Balance Sheet Preview (Layout: {layout_balance}):")
    #display(balance_df.head())
    #balance_map = parse_statement(balance_df, 'balance')
    #print("Mapped keys:", list(balance_map.keys()))

if cashflow_df is not None:
    print("\n💸 Cash Flow Preview:")
    display(cashflow_df.head())
    #cashflow_df, layout_cashflow = smart_layout_parser(cashflow_df)
   # print(f"\n💸 Cash Flow Preview (Layout: {layout_cashflow}):")
    #display(cashflow_df.head())

📄 Available Sheets in File:
0: Cover Page
1: Audit Information
2: Consolidated Statements of Inco
3: Consolidated Statements of Comp
4: Consolidated Balance Sheets
5: Consolidated Statements of Shar
6: Consolidated Statements of Sh_2
7: Consolidated Statements of Cash
8: Summary of Significant Accounti
9: Net Income Per Common Share
10: Shareholders' Equity
11: Accumulated Other Comprehensive
12: Accrued Liabilities
13: Short-term Borrowings and Long-
14: Leases
15: Fair Value Measurements
16: Taxes
17: Contingencies
18: Retirement-Related Benefits
19: Segments and Disaggregated Reve
20: Subsequent Event
21: Pay vs Performance Disclosure
22: Insider Trading Arrangements
23: Insider Trading Policies and Pr
24: Cybersecurity Risk Management a
25: Summary of Significant Accoun_2
26: Summary of Significant Accoun_3
27: Net Income Per Common Share (Ta
28: Shareholders' Equity (Tables)
29: Accumulated Other Comprehensi_2
30: Accrued Liabilities (Tables)
31: Short-term Borrowings and Lon_2
32: Leases (Tables)
33: Fair Value Measurements (Tables
34: Taxes (Tables)
35: Retirement-Related Benefits (Ta
36: Segments and Disaggregated Re_2
37: Subsequent Event (Tables)
38: Summary of Significant Accoun_4
39: Summary of Significant Accoun_5
40: Summary of Significant Accoun_6
41: Summary of Significant Accoun_7
42: Net Income Per Common Share - S
43: Shareholders' Equity - Narrativ
44: Shareholders' Equity - Share-Ba
45: Shareholders' Equity - Rollforw
46: Shareholders' Equity - Schedule
47: Shareholders' Equity - Schedu_2
48: Accumulated Other Comprehensi_3
49: Accrued Liabilities - Schedule
50: Short-term Borrowings and Lon_3
51: Short-term Borrowings and Lon_4
52: Short-term Borrowings and Lon_5
53: Short-term Borrowings and Lon_6
54: Short-term Borrowings and Lon_7
55: Short-term Borrowings and Lon_8
56: Leases - Leases Cost (Details)
57: Leases - Schedule of Other Info
58: Leases - Lessee Liability Matur
59: Fair Value Measurements - Recur
60: Fair Value Measurements - Notio
61: Fair Value Measurements - Narra
62: Fair Value Measurements - Carry
63: Taxes - Schedule of Income Befo
64: Taxes - Schedule of Income Tax
65: Taxes - Narrative (Details)
66: Taxes - Schedule of Income Ta_2
67: Taxes - Schedule of Deferred Ta
68: Taxes - Schedule of Deferred _2
69: Taxes - Reconciliation of Unrec
70: Contingencies (Details)
71: Retirement-Related Benefits - N
72: Retirement-Related Benefits - S
73: Segments and Disaggregated Re_3
74: Segments and Disaggregated Re_4
75: Segments and Disaggregated Re_5
76: Segments and Disaggregated Re_6
77: Segments and Disaggregated Re_7
78: Segments and Disaggregated Re_8
79: Subsequent Event (Details)

Enter the sheet number for the financial statements you have:
If you don't have one, just press Enter.

📊 Income Statement:  2
📘 Balance Sheet:  4
💸 Cash Flow Statement:  7

✅ Selected sheets loaded successfully.

📊 Income Statement Preview:

,"Consolidated Statements of Income - USD ($) shares in Millions, $ in Millions",12 Months Ended,Unnamed: 2,Unnamed: 3
0,NaN,"Jan. 31, 2025","Jan. 31, 2024","Jan. 31, 2023"
1,Revenues:,,,
2,Net sales,674538,642637,605881
3,Membership and other income,6447,5488,5408
4,Total revenues,680985,648125,611289

📘 Balance Sheet Preview:

,Consolidated Balance Sheets - USD ($) $ in Millions,"Jan. 31, 2025","Jan. 31, 2024"
0,Current assets:,,
1,Cash and cash equivalents,9037,9867
2,"Receivables, net",9975,8796
3,Inventories,56435,54892
4,Prepaid expenses and other,4011,3322

💸 Cash Flow Preview:

,Consolidated Statements of Cash Flows - USD ($) $ in Millions,12 Months Ended,Unnamed: 2,Unnamed: 3
0,NaN,"Jan. 31, 2025","Jan. 31, 2024","Jan. 31, 2023"
1,Cash flows from operating activities:,,,
2,Consolidated net income,20157,16270,11292
3,Adjustments to reconcile consolidated net inco...,,,
4,Depreciation and amortization,12973,11853,10945

In [6]:



balance_map = extract_financial_data(balance_df, 'balance')
print("Mapped keys:", list(balance_map.keys()))
for key, value in balance_map.items():
    print(f"{key}: {value}")
#unittest.main(argv=[''], exit=False)

Mapped keys: ['data', 'validation', 'stats']
data: {'cash_equivalents': Jan. 31, 2025    9037
Jan. 31, 2024    9867
Name: cash and cash equivalents, dtype: int64, 'receivables': Jan. 31, 2025    9975
Jan. 31, 2024    8796
Name: receivables net, dtype: int64, 'inventory': Jan. 31, 2025    56435
Jan. 31, 2024    54892
Name: inventories, dtype: int64, 'prepaid_expenses': Jan. 31, 2025    4011
Jan. 31, 2024    3322
Name: prepaid expenses and other, dtype: int64, 'current_assets': Jan. 31, 2025    79458
Jan. 31, 2024    76877
Name: total current assets, dtype: int64, 'property_plant_equipment': Jan. 31, 2025    119993
Jan. 31, 2024    110810
Name: property and equipment net, dtype: int64, 'operating_lease_assets': Jan. 31, 2025    13599
Jan. 31, 2024    13673
Name: operating lease rightofuse assets, dtype: int64, 'finance_lease_assets': Jan. 31, 2025    6112
Jan. 31, 2024    5855
Name: finance lease rightofuse assets net, dtype: int64, 'goodwill': Jan. 31, 2025    28792
Jan. 31, 2024    28113
Name: goodwill, dtype: int64, 'other_long_term_assets': Jan. 31, 2025    12869
Jan. 31, 2024    17071
Name: other longterm assets, dtype: int64, 'total_assets': Jan. 31, 2025    260823
Jan. 31, 2024    252399
Name: total assets, dtype: int64, 'short_term_borrowings': Jan. 31, 2025    3068
Jan. 31, 2024     878
Name: shortterm borrowings, dtype: int64, 'accounts_payable': Jan. 31, 2025    58666
Jan. 31, 2024    56812
Name: accounts payable, dtype: int64, 'accrued_liabilities': Jan. 31, 2025    29345
Jan. 31, 2024    28759
Name: accrued liabilities, dtype: int64, 'accrued_income_taxes': Jan. 31, 2025    608
Jan. 31, 2024    307
Name: accrued income taxes, dtype: int64, 'long_term_debt': Jan. 31, 2025    33401
Jan. 31, 2024    36132
Name: longterm debt, dtype: int64, 'operating_lease_liabilities': Jan. 31, 2025    1499
Jan. 31, 2024    1487
Name: operating lease obligations due within one year, dtype: int64, 'finance_lease_liabilities': Jan. 31, 2025    800
Jan. 31, 2024    725
Name: finance lease obligations due within one year, dtype: int64, 'current_liabilities': Jan. 31, 2025    96584
Jan. 31, 2024    92415
Name: total current liabilities, dtype: int64, 'noncurrent_operating_lease_liabilities': Jan. 31, 2025    12825
Jan. 31, 2024    12943
Name: longterm operating lease obligations, dtype: int64, 'noncurrent_finance_lease_liabilities': Jan. 31, 2025    5923
Jan. 31, 2024    5709
Name: longterm finance lease obligations, dtype: int64, 'deferred_taxes': Jan. 31, 2025    14398
Jan. 31, 2024    14629
Name: deferred income taxes and other, dtype: int64, 'redeemable_noncontrolling_interest': Jan. 31, 2025    6408
Jan. 31, 2024    6488
Name: nonredeemable noncontrolling interest, dtype: int64, 'common_stock': Jan. 31, 2025    802
Jan. 31, 2024    805
Name: common stock, dtype: int64, 'capital_in_excess_of_par_value': Jan. 31, 2025    5503
Jan. 31, 2024    4544
Name: capital in excess of par value, dtype: int64, 'retained_earnings': Jan. 31, 2025    98313
Jan. 31, 2024    89814
Name: retained earnings, dtype: int64, 'accumulated_other_comprehensive_loss': Jan. 31, 2025   -13605
Jan. 31, 2024   -11302
Name: accumulated other comprehensive loss, dtype: int64, 'total_shareholders_equity': Jan. 31, 2025    97421
Jan. 31, 2024    90349
Name: total shareholders equity, dtype: int64, 'grand_total_liabilities_equity': Jan. 31, 2025    260823
Jan. 31, 2024    252399
Name: total liabilities redeemable noncontrolling interest and shareholders equity, dtype: int64}
validation: {'section': 'balance', 'valid': False}
stats: {'matched': 32, 'skipped': 0}

In [7]:
income_map = extract_financial_data(income_df, 'income')
print("Mapped keys:", list(income_map.keys()))
for key, value in income_map.items():
    print(f"{key}: {value}")

Mapped keys: ['data', 'validation', 'stats']
data: {'net_sales': Jan. 31, 2025    674538
Jan. 31, 2024    642637
Jan. 31, 2023    605881
Name: net sales, dtype: int64, 'membership_and_other_income': Jan. 31, 2025    6447
Jan. 31, 2024    5488
Jan. 31, 2023    5408
Name: membership and other income, dtype: int64, 'total_revenue': Jan. 31, 2025    680985
Jan. 31, 2024    648125
Jan. 31, 2023    611289
Name: total revenues, dtype: int64, 'cost_of_sales': Jan. 31, 2025    511753
Jan. 31, 2024    490142
Jan. 31, 2023    463721
Name: cost of sales, dtype: int64, 'operating_expenses': Jan. 31, 2025    139884
Jan. 31, 2024    130971
Jan. 31, 2023    127140
Name: operating selling general and administrative expenses, dtype: int64, 'operating_income': Jan. 31, 2025    29348
Jan. 31, 2024    27012
Jan. 31, 2023    20428
Name: operating income, dtype: int64, 'interest_expense': Jan. 31, 2025    2245
Jan. 31, 2024    2137
Jan. 31, 2023    1874
Name: interest net, dtype: int64, 'finance_lease_expense': Jan. 31, 2025    479
Jan. 31, 2024    424
Jan. 31, 2023    341
Name: finance lease, dtype: int64, 'interest_income': Jan. 31, 2025   -483
Jan. 31, 2024   -546
Jan. 31, 2023   -254
Name: interest income, dtype: int64, 'other_gains_losses': Jan. 31, 2025     794
Jan. 31, 2024    3027
Jan. 31, 2023    1538
Name: other gains and losses, dtype: int64, 'pre_tax_income': Jan. 31, 2025    26309
Jan. 31, 2024    21848
Jan. 31, 2023    17016
Name: income before income taxes, dtype: int64, 'tax_expense': Jan. 31, 2025    6152
Jan. 31, 2024    5578
Jan. 31, 2023    5724
Name: provision for income taxes, dtype: int64, 'net_income': Jan. 31, 2025    19436
Jan. 31, 2024    15511
Jan. 31, 2023    11680
Name: consolidated net income attributable to walmart, dtype: int64, 'noncontrolling_interest': Jan. 31, 2025   -721
Jan. 31, 2024   -759
Jan. 31, 2023    388
Name: consolidated net income loss attributable to noncontrolling interest, dtype: int64, 'basic_eps': Jan. 31, 2025    2.42
Jan. 31, 2024    1.92
Jan. 31, 2023    1.43
Name: basic net income per common share attributable to walmart in usd per share, dtype: float64, 'diluted_eps': Jan. 31, 2025    2.41
Jan. 31, 2024    1.91
Jan. 31, 2023    1.42
Name: diluted net income per common share attributable to walmart in usd per share, dtype: float64, 'shares_basic': Jan. 31, 2025    8041
Jan. 31, 2024    8077
Jan. 31, 2023    8171
Name: basic in shares, dtype: int64, 'shares_diluted': Jan. 31, 2025    8081
Jan. 31, 2024    8108
Jan. 31, 2023    8202
Name: diluted in shares, dtype: int64, 'dividend_per_share': Jan. 31, 2025    0.8300
Jan. 31, 2024    0.7600
Jan. 31, 2023    0.7467
Name: dividends declared per common share in usd per share, dtype: float64}
validation: {'section': 'income', 'valid': True}
stats: {'matched': 21, 'skipped': 0}

In [8]:
cashflow_map = extract_financial_data(cashflow_df, 'cashflow')
print("Mapped keys:", list(cashflow_map.keys()))
for key, value in cashflow_map.items():
    print(f"{key}: {value}")

Mapped keys: ['data', 'validation', 'stats']
data: {'net_income': Jan. 31, 2025    20157
Jan. 31, 2024    16270
Jan. 31, 2023    11292
Name: consolidated net income, dtype: int64, 'depreciation_amortization': Jan. 31, 2025    12973
Jan. 31, 2024    11853
Jan. 31, 2023    10945
Name: depreciation and amortization, dtype: int64, 'investing_gains_losses': Jan. 31, 2025     878
Jan. 31, 2024    3193
Jan. 31, 2023    1683
Name: investment gains and losses net, dtype: int64, 'deferred_taxes': Jan. 31, 2025   -635
Jan. 31, 2024   -175
Jan. 31, 2023    449
Name: deferred income taxes, dtype: int64, 'other_operating_activities': Jan. 31, 2025    2889
Jan. 31, 2024    2642
Jan. 31, 2023    1919
Name: other operating activities, dtype: int64, 'changes_in_receivables': Jan. 31, 2025   -1106
Jan. 31, 2024    -797
Jan. 31, 2023     240
Name: receivables net, dtype: int64, 'changes_in_inventory': Jan. 31, 2025   -2755
Jan. 31, 2024    2017
Jan. 31, 2023    -528
Name: inventories, dtype: int64, 'changes_in_payables': Jan. 31, 2025    3228
Jan. 31, 2024    2515
Jan. 31, 2023   -1425
Name: accounts payable, dtype: int64, 'changes_in_accrued_liabilities': Jan. 31, 2025     379
Jan. 31, 2024   -1324
Jan. 31, 2023    4393
Name: accrued liabilities, dtype: int64, 'changes_in_income_taxes': Jan. 31, 2025    435
Jan. 31, 2024   -468
Jan. 31, 2023   -127
Name: accrued income taxes, dtype: int64, 'net_cash_operating': Jan. 31, 2025    36443
Jan. 31, 2024    35726
Jan. 31, 2023    28841
Name: net cash provided by operating activities, dtype: int64, 'capital_expenditure': Jan. 31, 2025   -23783
Jan. 31, 2024   -20606
Jan. 31, 2023   -16857
Name: payments for property and equipment, dtype: int64, 'proceeds_from_disposal': Jan. 31, 2025    4080
Jan. 31, 2024       0
Jan. 31, 2023       0
Name: proceeds from disposal of certain strategic investments, dtype: int64, 'business_acquisitions': Jan. 31, 2025   -1896
Jan. 31, 2024      -9
Jan. 31, 2023    -740
Name: payments for business acquisitions net of cash acquired, dtype: int64, 'other_investing_activities': Jan. 31, 2025   -212
Jan. 31, 2024   -922
Jan. 31, 2023   -295
Name: other investing activities, dtype: int64, 'net_cash_investing': Jan. 31, 2025   -21379
Jan. 31, 2024   -21287
Jan. 31, 2023   -17722
Name: net cash used in investing activities, dtype: int64, 'short_term_borrowings': Jan. 31, 2025    2212
Jan. 31, 2024     512
Jan. 31, 2023     -34
Name: net change in shortterm borrowings, dtype: int64, 'debt_issuance': Jan. 31, 2025       0
Jan. 31, 2024    4967
Jan. 31, 2023    5041
Name: proceeds from issuance of longterm debt, dtype: int64, 'debt_repayments': Jan. 31, 2025   -3468
Jan. 31, 2024   -4217
Jan. 31, 2023   -2689
Name: repayments of longterm debt, dtype: int64, 'dividends_paid_to_nci': Jan. 31, 2025   -576
Jan. 31, 2024   -763
Jan. 31, 2023   -444
Name: dividends paid to noncontrolling interest, dtype: int64, 'purchase_of_stock': Jan. 31, 2025   -4494
Jan. 31, 2024   -2779
Jan. 31, 2023   -9920
Name: purchase of company stock, dtype: int64, 'purchase_noncontrolling_interest': Jan. 31, 2025       0
Jan. 31, 2024   -3462
Jan. 31, 2023    -827
Name: purchase of noncontrolling interest, dtype: int64, 'proceeds_from_subsidiary_stock_sale': Jan. 31, 2025    362
Jan. 31, 2024    716
Jan. 31, 2023     66
Name: sale of subsidiary stock, dtype: int64, 'other_financing_activities': Jan. 31, 2025   -2170
Jan. 31, 2024   -2248
Jan. 31, 2023   -2118
Name: other financing activities, dtype: int64, 'net_cash_financing': Jan. 31, 2025   -14822
Jan. 31, 2024   -13414
Jan. 31, 2023   -17039
Name: net cash used in financing activities, dtype: int64, 'fx_effect_on_cash': Jan. 31, 2025   -641
Jan. 31, 2024     69
Jan. 31, 2023    -73
Name: effect of exchange rates on cash cash equivalents and restricted cash, dtype: int64, 'net_increase_cash': Jan. 31, 2025    -399
Jan. 31, 2024    1094
Jan. 31, 2023   -5993
Name: net increase decrease in cash cash equivalents and restricted cash, dtype: int64, 'cash_beginning': Jan. 31, 2025     9935
Jan. 31, 2024     8841
Jan. 31, 2023    14834
Name: cash cash equivalents and restricted cash at beginning of year, dtype: int64, 'cash_end': Jan. 31, 2025    9536
Jan. 31, 2024    9935
Jan. 31, 2023    8841
Name: cash cash equivalents and restricted cash at end of year, dtype: int64, 'income_taxes_paid': Jan. 31, 2025    5884
Jan. 31, 2024    5879
Jan. 31, 2023    3310
Name: income taxes paid, dtype: int64, 'interest_paid': Jan. 31, 2025    2739
Jan. 31, 2024    2519
Jan. 31, 2023    2051
Name: interest paid, dtype: int64}
validation: {'section': 'cashflow', 'valid': True}
stats: {'matched': 33, 'skipped': 0}

In [9]:
import importlib
import ratio
importlib.reload(ratio)
from ratio import RatioEngine
engine = RatioEngine(income_map, balance_map, cashflow_map)
engine.interactive_analytics()

...... BACKGROUND PROCESSES ......
  Starting financial analytics •
============================================================
MARKET PRICE REQUIRED FOR VALUATION RATIOS (2023)
============================================================
Valuation ratios require the market price per share.
Please provide the closing stock price at the end of the fiscal year.
If you don't know the price, press Enter to skip valuation ratios.

Enter market price per share for 2023 (or press Enter to skip):  52.55

============================================================
MARKET PRICE REQUIRED FOR VALUATION RATIOS (2024)
============================================================
Valuation ratios require the market price per share.
Please provide the closing stock price at the end of the fiscal year.
If you don't know the price, press Enter to skip valuation ratios.

Enter market price per share for 2024 (or press Enter to skip):  90.78

============================================================
MARKET PRICE REQUIRED FOR VALUATION RATIOS (2025)
============================================================
Valuation ratios require the market price per share.
Please provide the closing stock price at the end of the fiscal year.
If you don't know the price, press Enter to skip valuation ratios.

Enter market price per share for 2025 (or press Enter to skip):  100.62

================================================================================
                      INITIAL FINANCIAL HEALTH ASSESSMENT
================================================================================

Key Observations:
 - 📈 Profitability: 2/2 key ratios improving
 - 💧 Liquidity: Moderate position
 - 💰 Valuation: Overvalued (P/E: 41.63)
 - 🏦 Leverage: Low debt (D/E: 0.34)

================================================================================
For detailed analysis of individual ratios, select option 1
For a comprehensive financial health report, select option 4
================================================================================


Before we begin, please specify your industry for more relevant analysis.
Available industries: Technology, Manufacturing, Retail

Enter your industry (or press Enter to skip):  Retail

Industry set to: Retail

✅ System Init COMPLETE

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  1
Enter ratio Analysis Code (e.g., current_ratio):  pe

⚠️ Ratio 'pe' not found. Available ratios:
gross_margin, net_margin, return_on_equity, operating_margin, net_profit_margin, current_ratio, quick_ratio, debt_to_equity, interest_coverage, inventory_turnover, asset_turnover, eps, pe_ratio, ebitda

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  ebitda

Invalid option. Please try again.

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  1
Enter ratio Analysis Code (e.g., current_ratio):  ebitda

============================================================
RESULTS FOR EBITDA
============================================================
Description: Earnings Before Interest, Taxes, Depreciation, and Amortization

+--------+-----------------------------------------------------------------------------+
| Year   | Calculation                                                                 |
+========+=============================================================================+
| 2023   | Operating Income (20,428) + Depreciation & Amortization (10,945) = 31373.00 |
+--------+-----------------------------------------------------------------------------+
| 2024   | Operating Income (27,012) + Depreciation & Amortization (11,853) = 38865.00 |
+--------+-----------------------------------------------------------------------------+
| 2025   | Operating Income (29,348) + Depreciation & Amortization (12,973) = 42321.00 |
+--------+-----------------------------------------------------------------------------+

TREND ANALYSIS:
The ratio shows a positive trend, increasing from 31373.00 in 2023 to 42321.00 in 2025 (+34.90%). This improvement suggests enhanced financial performance in this area.

Year-over-Year Changes:
+-----------+----------+
| Period    | Change   |
+===========+==========+
| 2023-2024 | +23.88%  |
+-----------+----------+
| 2024-2025 | +8.89%   |
+-----------+----------+

============================================================


ASK QUESTIONS ABOUT EBITDA (type 'exit' to finish)
============================================================

Suggested questions based on your data:
1. What are the components of this ratio?
2. How can a company improve this ratio?
3. What factors influence this ratio?
4. How does this compare to Retail industry averages?
5. What's driving the improvement in this ratio?

Your question:  5

----------------------ANALYST INSIGHT-----------------------
The EBITDA for the years provided is calculated as follows: for 2023, it is $31,373 (Operating Income of $20,428 plus Depreciation & Amortization of $10,945). In 2024, it rises to $38,865, and in 2025, it reaches $42,321, indicating a positive growth trend in earnings before accounting for interest, taxes, depreciation, and amortization. This growth suggests improving operational efficiency and potentially higher profitability. To capitalize on this trend, consider investing in areas that enhance operational performance or reduce costs further.
------------------------------------------------------------

Your question:  exit

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  4

Generating comprehensive financial health report...

================================================================================
                     COMPREHENSIVE FINANCIAL HEALTH REPORT
================================================================================
### Comprehensive Financial Health Report

#### 1. Executive Summary of Overall Financial Health
The financial health of the organization shows a positive trajectory, characterized by improving profitability metrics and a stable financial leverage position. The net margin, operating margin, and return on equity are all on an upward trend, indicating effective cost management and enhanced shareholder value. However, liquidity ratios show a slight decline, suggesting a need for improved short-term financial management. Overall, the company is positioned for growth, but attention to liquidity and operational efficiency is recommended to sustain this momentum.

#### 2. Analysis by Category

**Profitability:**
- **Net Margin:** Increased from 1.91% in 2023 to 2.85% in 2025 (+49.2%). This indicates improved cost control and pricing strategies.
- **Operating Margin:** Rose from 3.34% in 2023 to 4.31% in 2025 (+29.0%), reflecting enhanced operational efficiency.
- **Return on Equity (ROE):** Projected to grow from 17.17% in 2024 to 19.95% in 2025 (+16.2%), demonstrating effective use of equity capital.
- **Earnings Per Share (EPS):** Expected to increase from 1.4294 in 2023 to 2.4171 in 2025 (+69.1%), signaling strong profit growth on a per-share basis.

**Liquidity:**
- **Current Ratio:** Decreased slightly from 0.83 in 2024 to 0.82 in 2025 (-1.1%). This indicates a marginal decline in the ability to cover short-term liabilities, warranting attention.

**Leverage:**
- **Debt-to-Equity Ratio:** Improved from 0.40 in 2024 to 0.34 in 2025 (-14.3%), suggesting reduced financial risk and a stronger equity base.
- **Interest Coverage:** Increased from 10.90 in 2023 to 13.07 in 2025 (+19.9%), indicating a robust capacity to meet interest obligations.

**Efficiency:**
- **Asset Turnover:** Slight increase from 2.57 in 2024 to 2.61 in 2025 (+1.7%), reflecting stable asset utilization.

**Valuation:**
- **Price-to-Earnings (P/E) Ratio:** Fluctuated from 36.76 in 2023 to 41.63 in 2025 (+13.2%), indicating market expectations of future growth.

#### 3. Key Strengths and Weaknesses

**Strengths:**
- Strong growth in profitability metrics (net margin, operating margin, ROE).
- Significant improvement in EPS, indicating effective profit generation.
- Decreasing debt-to-equity ratio, reflecting lower financial risk.
- High interest coverage ratio, showcasing the ability to manage debt obligations comfortably.

**Weaknesses:**
- Declining current ratio indicates potential liquidity concerns.
- Fluctuating P/E ratio suggests market uncertainty regarding future earnings stability.

#### 4. Recommendations for Improvement
- **Enhance Liquidity Management:** Focus on improving the current ratio by optimizing working capital management, such as reducing inventory levels and improving receivables collection.
- **Cost Control Initiatives:** Continue to identify and implement cost-saving measures to maintain or further improve margins.
- **Strategic Investments:** Consider reinvesting profits into high-return projects to sustain growth in EPS and ROE.
- **Market Communication:** Improve transparency and communication with investors regarding future growth strategies to stabilize P/E fluctuations.

#### 5. Future Outlook
The outlook for the company appears positive, with projected growth in profitability and shareholder returns. Continued focus on operational efficiency and prudent financial management will be crucial in navigating potential liquidity challenges. If the company can successfully enhance its liquidity position while sustaining profitability growth, it is well-positioned to capitalize on market opportunities and deliver long-term value to shareholders.
================================================================================

Report saved to financial_report_20251031_224443.txt

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  exit

Invalid option. Please try again.

================================================================================
                           FINANCIAL RATIO DASHBOARD
================================================================================
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+==========================+================================+==========================================+=================+=================+
| Ratio                    | Values (2023 | 2024 | 2025)    | Description                              | Trend           | Analysis Code   |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| --------------------     | ------------------------------ | ---------------------------------------- | --------------- | --------------- |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Margin ↑             | 2023: 1.91% | 2024: 2.39% |    | Measures overall profitability           | Improving       | [net_margin]    |
|                          | 2025: 2.85%                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Return on Equity (ROE) ↑ | 2023: - | 2024: 17.17% | 2025: | Measures return generated on shareholder | Improving       | [return_on_equi |
|                          | 19.95%                         | investment                               |                 | ty]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Operating Margin ↑       | 2023: 3.34% | 2024: 4.17% |    | Measures profitability from core         | Improving       | [operating_marg |
|                          | 2025: 4.31%                    | operations                               |                 | in]             |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Net Profit Margin ↑      | 2023: 1.91 | 2024: 2.39 |      | it tells profit per total sales done     | Improving       | [net_profit_mar |
|                          | 2025: 2.85                     |                                          |                 | gin]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Current Ratio ↓          | 2023: - | 2024: 0.83 | 2025:   | Measures ability to pay short-term       | Declining       | [current_ratio] |
|                          | 0.82                           | obligations                              |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Debt-to-Equity Ratio ↓   | 2023: - | 2024: 0.40 | 2025:   | Measures financial leverage and risk     | Declining       | [debt_to_equity |
|                          | 0.34                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Interest Coverage ↑      | 2023: 10.90 | 2024: 12.64 |    | Measures ability to pay interest         | Improving       | [interest_cover |
|                          | 2025: 13.07                    | expenses                                 |                 | age]            |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Asset Turnover ↑         | 2023: - | 2024: 2.57 | 2025:   | Measures efficiency of asset utilization | Improving       | [asset_turnover |
|                          | 2.61                           |                                          |                 | ]               |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Earnings Per Share (EPS) | 2023: 1.4294 | 2024: 1.9204 |  | Earnings per common share outstanding    | Improving       | [eps]           |
| ↑                        | 2025: 2.4171                   |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| Pe Ratio ↕               | 2023: 36.76 | 2024: 47.27 |    | Price-to-earnings valuation ratio        | Fluctuating     | [pe_ratio]      |
|                          | 2025: 41.63                    |                                          |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
| EBITDA ↑                 | 2023: 31373.00 | 2024:         | Earnings Before Interest, Taxes,         | Improving       | [ebitda]        |
|                          | 38865.00 | 2025: 42321.00      | Depreciation, and Amortization           |                 |                 |
+--------------------------+--------------------------------+------------------------------------------+-----------------+-----------------+
================================================================================
To view detailed analysis, enter the ratio's Analysis Code (e.g., current_ratio)
================================================================================

Options:
1. View detailed ratio analysis
2. Calculate custom ratio
3. Ask about a specific ratio
4. Generate comprehensive financial health report
5. Delete a custom ratio
6. Reset ratios
7. Exit

Select an option:  7

Exiting financial analytics system